development:
  adapter: postgresql
  encoding: unicode
  database: health_development
  pool: 5
  username: ndonias
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: health_test
  pool: 5
  username: ndonias
  password:
